name = "NewJuliaaRepo"
author = "Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"
uuid = "6df7ddd1-d8ee-42ee-b24f-9840d2df4c3d"
version = "0.1.0"

[deps]
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"
PkgSkeleton = "d254efa0-af53-535e-b7f1-03c1c9fbcbe7"

[compat]
PkgTemplates = "0.7 - 0.9"
PkgSkeleton = "1.2"
julia = "1.10"
